name: frifalca_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0' # Actualizado para compatibilidad

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Firebase Core
  firebase_core: ^2.31.0

  # Firebase Services
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.4
  firebase_messaging: ^14.9.2 # Para notificaciones push

  # Notificaciones locales (para mostrar la notificación cuando la app está abierta)
  flutter_local_notifications: ^17.1.2

  # Auth & HTTP
  googleapis_auth: ^1.5.1
  http: ^1.2.1

  # Otros
  local_auth: ^2.2.0
  shared_preferences: ^2.2.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 # Ajustado a una versión estable
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/frifalca6.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/frifalca6.png
